import type { Event, Booking } from "./schemas"

function generateBookingCode(): string {
  const chars = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789"
  let code = "EVT-"
  for (let i = 0; i < 5; i++) {
    code += chars.charAt(Math.floor(Math.random() * chars.length))
  }
  return code
}

const now = new Date()
const tomorrow = new Date(now.getTime() + 24 * 60 * 60 * 1000)
const nextWeek = new Date(now.getTime() + 7 * 24 * 60 * 60 * 1000)
const nextMonth = new Date(now.getTime() + 30 * 24 * 60 * 60 * 1000)

export const initialEvents: Event[] = [
  {
    id: "evt-1",
    title: "Tech Startup Networking Night",
    shortDescription: "Connect with founders, investors, and tech enthusiasts in Warsaw's vibrant startup scene.",
    longDescription: "Join us for an evening of networking, lightning talks, and discussions about the latest trends in technology and entrepreneurship. Whether you're a seasoned founder or just curious about the startup world, this event is perfect for making meaningful connections.",
    location: "WeWork Mennica Legacy, Warsaw",
    onlineUrl: "",
    coverImageUrl: "",
    startDateTime: tomorrow.toISOString(),
    endDateTime: new Date(tomorrow.getTime() + 3 * 60 * 60 * 1000).toISOString(),
    timezone: "Europe/Warsaw",
    capacity: 50,
    bookingType: "free",
    tags: ["networking", "tech", "startup"],
    status: "published",
    organizerName: "Warsaw Tech Hub",
    organizerEmail: "events@warsawtechhub.com",
    createdAt: new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "evt-2",
    title: "Advanced React Workshop",
    shortDescription: "Deep dive into React 19, Server Components, and modern patterns with hands-on exercises.",
    longDescription: "This intensive workshop covers advanced React concepts including Server Components, Suspense, concurrent features, and performance optimization. Bring your laptop and get ready to code! Lunch and refreshments included in the ticket price.",
    location: "Google Campus Warsaw",
    onlineUrl: "https://meet.google.com/abc-defg-hij",
    coverImageUrl: "",
    startDateTime: nextWeek.toISOString(),
    endDateTime: new Date(nextWeek.getTime() + 8 * 60 * 60 * 1000).toISOString(),
    timezone: "Europe/Warsaw",
    capacity: 30,
    bookingType: "ticketed",
    price: 199,
    tags: ["workshop", "react", "programming"],
    status: "published",
    organizerName: "Code Academy",
    organizerEmail: "workshops@codeacademy.pl",
    createdAt: new Date(now.getTime() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(now.getTime() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "evt-3",
    title: "AI Ethics Roundtable",
    shortDescription: "Invitation-only discussion on responsible AI development with industry leaders.",
    longDescription: "An intimate gathering of AI researchers, ethicists, and policy makers to discuss the challenges and opportunities in responsible AI development. This is an approval-based event to ensure diverse perspectives and meaningful dialogue.",
    location: "University of Warsaw, Main Hall",
    onlineUrl: "",
    coverImageUrl: "",
    startDateTime: new Date(nextMonth.getTime() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    endDateTime: new Date(nextMonth.getTime() + 2 * 24 * 60 * 60 * 1000 + 4 * 60 * 60 * 1000).toISOString(),
    timezone: "Europe/Warsaw",
    capacity: 20,
    bookingType: "approval",
    tags: ["ai", "ethics", "discussion"],
    status: "published",
    organizerName: "AI Research Institute",
    organizerEmail: "events@airesearch.edu.pl",
    createdAt: new Date(now.getTime() - 21 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "evt-4",
    title: "Summer Music Festival",
    shortDescription: "A full day of live music featuring local and international artists.",
    longDescription: "Experience the best of summer with an all-day music festival featuring multiple stages, food vendors, and art installations. Early bird tickets available now!",
    location: "Lazienki Park, Warsaw",
    onlineUrl: "",
    coverImageUrl: "",
    startDateTime: new Date(nextMonth.getTime() + 15 * 24 * 60 * 60 * 1000).toISOString(),
    endDateTime: new Date(nextMonth.getTime() + 15 * 24 * 60 * 60 * 1000 + 10 * 60 * 60 * 1000).toISOString(),
    timezone: "Europe/Warsaw",
    capacity: 5,
    bookingType: "ticketed",
    price: 89,
    tags: ["music", "festival", "outdoor"],
    status: "published",
    organizerName: "Warsaw Events Co",
    organizerEmail: "info@warsawevents.pl",
    createdAt: new Date(now.getTime() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(now.getTime() - 10 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "evt-5",
    title: "Product Design Sprint",
    shortDescription: "5-day intensive design sprint methodology workshop.",
    longDescription: "Learn and practice the Google Ventures design sprint methodology. Over 5 days, you'll work on a real problem and prototype a solution. This draft event is pending final venue confirmation.",
    location: "TBD - Design Studio",
    onlineUrl: "",
    coverImageUrl: "",
    startDateTime: new Date(nextMonth.getTime() + 20 * 24 * 60 * 60 * 1000).toISOString(),
    endDateTime: new Date(nextMonth.getTime() + 25 * 24 * 60 * 60 * 1000).toISOString(),
    timezone: "Europe/Warsaw",
    capacity: 15,
    bookingType: "ticketed",
    price: 599,
    tags: ["design", "workshop", "ux"],
    status: "draft",
    organizerName: "Design Thinking Lab",
    organizerEmail: "hello@dtlab.pl",
    createdAt: new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: now.toISOString(),
  },
  {
    id: "evt-6",
    title: "Community Yoga Session",
    shortDescription: "Free weekly yoga session for all skill levels in the park.",
    longDescription: "Join our friendly community for a relaxing hour of yoga. All levels welcome, from complete beginners to experienced practitioners. Bring your own mat or borrow one of ours.",
    location: "Pole Mokotowskie Park",
    onlineUrl: "",
    coverImageUrl: "",
    startDateTime: new Date(now.getTime() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    endDateTime: new Date(now.getTime() + 3 * 24 * 60 * 60 * 1000 + 1 * 60 * 60 * 1000).toISOString(),
    timezone: "Europe/Warsaw",
    capacity: 40,
    bookingType: "free",
    tags: ["yoga", "wellness", "outdoor", "free"],
    status: "published",
    organizerName: "Wellness Warsaw",
    organizerEmail: "contact@wellnesswarsaw.pl",
    createdAt: new Date(now.getTime() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
]

export const initialBookings: Booking[] = [
  {
    id: "bkg-1",
    eventId: "evt-1",
    attendeeName: "Jan Kowalski",
    attendeeEmail: "jan.kowalski@email.com",
    quantity: 2,
    status: "confirmed",
    bookingCode: generateBookingCode(),
    createdAt: new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "bkg-2",
    eventId: "evt-1",
    attendeeName: "Anna Nowak",
    attendeeEmail: "anna.nowak@email.com",
    quantity: 1,
    status: "confirmed",
    bookingCode: generateBookingCode(),
    createdAt: new Date(now.getTime() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "bkg-3",
    eventId: "evt-2",
    attendeeName: "Piotr Wisniewski",
    attendeeEmail: "piotr.w@email.com",
    quantity: 1,
    status: "confirmed",
    bookingCode: generateBookingCode(),
    createdAt: new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "bkg-4",
    eventId: "evt-3",
    attendeeName: "Maria Lewandowska",
    attendeeEmail: "m.lewandowska@university.pl",
    quantity: 1,
    status: "pending",
    bookingCode: generateBookingCode(),
    notes: "Professor of AI Ethics at Warsaw University",
    createdAt: new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "bkg-5",
    eventId: "evt-4",
    attendeeName: "Tomasz Zielinski",
    attendeeEmail: "tomasz.z@email.com",
    quantity: 2,
    status: "confirmed",
    bookingCode: generateBookingCode(),
    createdAt: new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "bkg-6",
    eventId: "evt-4",
    attendeeName: "Katarzyna Dabrowska",
    attendeeEmail: "kasia.d@email.com",
    quantity: 3,
    status: "waitlist",
    bookingCode: generateBookingCode(),
    createdAt: new Date(now.getTime() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "bkg-7",
    eventId: "evt-6",
    attendeeName: "Ewa Kaminska",
    attendeeEmail: "ewa.k@email.com",
    quantity: 1,
    status: "checked_in",
    bookingCode: generateBookingCode(),
    createdAt: new Date(now.getTime() - 4 * 24 * 60 * 60 * 1000).toISOString(),
  },
]

export { generateBookingCode }
